nodeLinker: node-modules

npmRegistries:
  "https://npm.runelab.it/":
    npmAuthToken: "${RUNELAB_TOKEN}"

npmScopes:
  fortawesome:
    npmAuthToken: "${RUNELAB_TOKEN}"
    npmRegistryServer: "https://npm.runelab.it/"
