export const NATIONS = [
  { it: 'Afghanistan', en: 'Afghanistan', value: 'AF' },
  { it: 'Albania', en: 'Albania', value: 'AL' },
  { it: 'Algeria', en: 'Algeria', value: 'DZ' },
  { it: 'Andorra', en: 'Andorra', value: 'AD' },
  { it: 'Angola', en: 'Angola', value: 'AO' },
  { it: 'Antigua e Barbuda', en: 'Antigua and Barbuda', value: 'AG' },
  { it: 'Arabia Saudita', en: 'Saudi Arabia', value: 'SA' },
  { it: 'Argentina', en: 'Argentina', value: 'AR' },
  { it: 'Armenia', en: 'Armenia', value: 'AM' },
  { it: 'Australia', en: 'Australia', value: 'AU' },
  { it: 'Austria', en: 'Austria', value: 'AT' },
  { it: 'Azerbaigian', en: 'Azerbaijan', value: 'AZ' },
  { it: 'Bahamas', en: 'Bahamas', value: 'BS' },
  { it: 'Bahrein', en: 'Bahrain', value: 'BH' },
  { it: 'Bangladesh', en: 'Bangladesh', value: 'BD' },
  { it: 'Barbados', en: 'Barbados', value: 'BB' },
  { it: 'Belgio', en: 'Belgium', value: 'BE' },
  { it: 'Belize', en: 'Belize', value: 'BZ' },
  { it: 'Benin', en: 'Benin', value: 'BJ' },
  { it: 'Bhutan', en: 'Bhutan', value: 'BT' },
  { it: 'Bielorussia', en: 'Belarus', value: 'BY' },
  { it: 'Birmania', en: 'Myanmar', value: 'MM' },
  { it: 'Bolivia', en: 'Bolivia', value: 'BO' },
  { it: 'Bosnia ed Erzegovina', en: 'Bosnia and Herzegovina', value: 'BA' },
  { it: 'Botswana', en: 'Botswana', value: 'BW' },
  { it: 'Brasile', en: 'Brazil', value: 'BR' },
  { it: 'Brunei', en: 'Brunei', value: 'BN' },
  { it: 'Bulgaria', en: 'Bulgaria', value: 'BG' },
  { it: 'Burkina Faso', en: 'Burkina Faso', value: 'BF' },
  { it: 'Burundi', en: 'Burundi', value: 'BI' },
  { it: 'Cambogia', en: 'Cambodia', value: 'KH' },
  { it: 'Camerun', en: 'Cameroon', value: 'CM' },
  { it: 'Canada', en: 'Canada', value: 'CA' },
  { it: 'Capo Verde', en: 'Cape Verde', value: 'CV' },
  { it: 'Ciad', en: 'Chad', value: 'TD' },
  { it: 'Cile', en: 'Chile', value: 'CL' },
  { it: 'Cina', en: 'China', value: 'CN' },
  { it: 'Cina', en: 'China', value: 'CN' },
  { it: 'Cipro', en: 'Cyprus', value: 'CY' },
  { it: 'Colombia', en: 'Colombia', value: 'CO' },
  { it: 'Comore', en: 'Comoros', value: 'KM' },
  { it: 'Corea del Nord', en: 'North Korea', value: 'KP' },
  { it: 'Corea del Sud', en: 'South Korea', value: 'KR' },
  { it: "Costa d'Avorio", en: 'Ivory Coast', value: 'CI' },
  { it: 'Costa Rica', en: 'Costa Rica', value: 'CR' },
  { it: 'Croazia', en: 'Croatia', value: 'HR' },
  { it: 'Cuba', en: 'Cuba', value: 'CU' },
  { it: 'Danimarca', en: 'Denmark', value: 'DK' },
  { it: 'Egitto', en: 'Egypt', value: 'EG' },
  { it: 'El Salvador', en: 'El Salvador', value: 'SV' },
  { it: 'Emirati Arabi Uniti', en: 'United Arab Emirates', value: 'AE' },
  { it: 'Eritrea', en: 'Eritrea', value: 'ER' },
  { it: 'Estonia', en: 'Estonia', value: 'EE' },
  { it: 'Etiopia', en: 'Ethiopia', value: 'ET' },
  { it: 'Figi', en: 'Fiji', value: 'FJ' },
  { it: 'Filippine', en: 'Philippines', value: 'PH' },
  { it: 'Finlandia', en: 'Finland', value: 'FI' },
  { it: 'Francia', en: 'France', value: 'FR' },
  { it: 'Gabon', en: 'Gabon', value: 'GA' },
  { it: 'Gambia', en: 'Gambia', value: 'GM' },
  { it: 'Georgia', en: 'Georgia', value: 'GE' },
  { it: 'Germania', en: 'Germany', value: 'DE' },
  { it: 'Ghana', en: 'Ghana', value: 'GH' },
  { it: 'Giamaica', en: 'Jamaica', value: 'JM' },
  { it: 'Giappone', en: 'Japan', value: 'JP' },
  { it: 'Gibuti', en: 'Djibouti', value: 'DJ' },
  { it: 'Giordania', en: 'Jordan', value: 'JO' },
  { it: 'Grecia', en: 'Greece', value: 'GR' },
  { it: 'Grenada', en: 'Grenada', value: 'GD' },
  { it: 'Groenlandia', en: 'Greenland', value: 'GL' },
  { it: 'Guatemala', en: 'Guatemala', value: 'GT' },
  { it: 'Guinea', en: 'Guinea', value: 'GN' },
  { it: 'Guinea-Bissau', en: 'Guinea-Bissau', value: 'GW' },
  { it: 'Guinea Equatoriale', en: 'Equatorial Guinea', value: 'GQ' },
  { it: 'Guyana', en: 'Guyana', value: 'GY' },
  { it: 'Haiti', en: 'Haiti', value: 'HT' },
  { it: 'Honduras', en: 'Honduras', value: 'HN' },
  { it: 'India', en: 'India', value: 'IN' },
  { it: 'Indonesia', en: 'Indonesia', value: 'ID' },
  { it: 'Iran', en: 'Iran', value: 'IR' },
  { it: 'Iraq', en: 'Iraq', value: 'IQ' },
  { it: 'Irlanda', en: 'Ireland', value: 'IE' },
  { it: 'Islanda', en: 'Iceland', value: 'IS' },
  { it: 'Israele', en: 'Israel', value: 'IL' },
  { it: 'Italia', en: 'Italy', value: 'IT' },
  { it: 'Kazakistan', en: 'Kazakhstan', value: 'KZ' },
  { it: 'Kenya', en: 'Kenya', value: 'KE' },
  { it: 'Kirghizistan', en: 'Kyrgyzstan', value: 'KG' },
  { it: 'Kiribati', en: 'Kiribati', value: 'KI' },
  { it: 'Kuwait', en: 'Kuwait', value: 'KW' },
  { it: 'Laos', en: 'Laos', value: 'LA' },
  { it: 'Lesotho', en: 'Lesotho', value: 'LS' },
  { it: 'Lettonia', en: 'Latvia', value: 'LV' },
  { it: 'Libano', en: 'Lebanon', value: 'LB' },
  { it: 'Liberia', en: 'Liberia', value: 'LR' },
  { it: 'Libia', en: 'Libya', value: 'LY' },
  { it: 'Liechtenstein', en: 'Liechtenstein', value: 'LI' },
  { it: 'Lituania', en: 'Lithuania', value: 'LT' },
  { it: 'Lussemburgo', en: 'Luxembourg', value: 'LU' },
  { it: 'Macao', en: 'Macao', value: 'MO' },
  { it: 'Macedonia del Nord', en: 'North Macedonia', value: 'MK' },
  { it: 'Madagascar', en: 'Madagascar', value: 'MG' },
  { it: 'Malawi', en: 'Malawi', value: 'MW' },
  { it: 'Malaysia', en: 'Malaysia', value: 'MY' },
  { it: 'Maldive', en: 'Maldives', value: 'MV' },
  { it: 'Mali', en: 'Mali', value: 'ML' },
  { it: 'Malta', en: 'Malta', value: 'MT' },
  { it: 'Marocco', en: 'Morocco', value: 'MA' },
  { it: 'Marshall', en: 'Marshall Islands', value: 'MH' },
  { it: 'Mauritania', en: 'Mauritania', value: 'MR' },
  { it: 'Mauritius', en: 'Mauritius', value: 'MU' },
  { it: 'Messico', en: 'Mexico', value: 'MX' },
  { it: 'Micronesia', en: 'Micronesia', value: 'FM' },
  { it: 'Moldavia', en: 'Moldova', value: 'MD' },
  { it: 'Monaco', en: 'Monaco', value: 'MC' },
  { it: 'Mongolia', en: 'Mongolia', value: 'MN' },
  { it: 'Montenegro', en: 'Montenegro', value: 'ME' },
  { it: 'Mozambico', en: 'Mozambique', value: 'MZ' },
  { it: 'Namibia', en: 'Namibia', value: 'NA' },
  { it: 'Nauru', en: 'Nauru', value: 'NR' },
  { it: 'Nepal', en: 'Nepal', value: 'NP' },
  { it: 'Nicaragua', en: 'Nicaragua', value: 'NI' },
  { it: 'Niger', en: 'Niger', value: 'NE' },
  { it: 'Nigeria', en: 'Nigeria', value: 'NG' },
  { it: 'Norvegia', en: 'Norway', value: 'NO' },
  { it: 'Nuova Zelanda', en: 'New Zealand', value: 'NZ' },
  { it: 'Oman', en: 'Oman', value: 'OM' },
  { it: 'Paesi Bassi', en: 'Netherlands', value: 'NL' },
  { it: 'Pakistan', en: 'Pakistan', value: 'PK' },
  { it: 'Palau', en: 'Palau', value: 'PW' },
  { it: 'Panama', en: 'Panama', value: 'PA' },
  { it: 'Papua Nuova Guinea', en: 'Papua New Guinea', value: 'PG' },
  { it: 'Paraguay', en: 'Paraguay', value: 'PY' },
  { it: 'Perù', en: 'Peru', value: 'PE' },
  { it: 'Polonia', en: 'Poland', value: 'PL' },
  { it: 'Portogallo', en: 'Portugal', value: 'PT' },
  { it: 'Qatar', en: 'Qatar', value: 'QA' },
  { it: 'Regno Unito', en: 'United Kingdom', value: 'GB' },
  { it: 'Repubblica Ceca', en: 'Czech Republic', value: 'CZ' },
  { it: 'Repubblica Centrafricana', en: 'Central African Republic', value: 'CF' },
  { it: 'Repubblica del Congo', en: 'Republic of the Congo', value: 'CG' },
  { it: 'Repubblica Democratica del Congo', en: 'Democratic Republic of the Congo', value: 'CD' },
  { it: 'Repubblica Dominicana', en: 'Dominican Republic', value: 'DO' },
  { it: 'Romania', en: 'Romania', value: 'RO' },
  { it: 'Ruanda', en: 'Rwanda', value: 'RW' },
  { it: 'Russia', en: 'Russia', value: 'RU' },
  { it: 'Rwanda', en: 'Rwanda', value: 'RW' },
  { it: 'Saint Kitts e Nevis', en: 'Saint Kitts and Nevis', value: 'KN' },
  { it: 'Saint Vincent e Grenadine', en: 'Saint Vincent and the Grenadines', value: 'VC' },
  { it: 'Samoa', en: 'Samoa', value: 'WS' },
  { it: 'San Marino', en: 'San Marino', value: 'SM' },
  { it: 'Sao Tomé e Principe', en: 'Sao Tome and Principe', value: 'ST' },
  { it: 'Senegal', en: 'Senegal', value: 'SN' },
  { it: 'Serbia', en: 'Serbia', value: 'RS' },
  { it: 'Seychelles', en: 'Seychelles', value: 'SC' },
  { it: 'Sierra Leone', en: 'Sierra Leone', value: 'SL' },
  { it: 'Singapore', en: 'Singapore', value: 'SG' },
  { it: 'Siria', en: 'Syria', value: 'SY' },
  { it: 'Slovacchia', en: 'Slovakia', value: 'SK' },
  { it: 'Slovenia', en: 'Slovenia', value: 'SI' },
  { it: 'Somalia', en: 'Somalia', value: 'SO' },
  { it: 'Spagna', en: 'Spain', value: 'ES' },
  { it: 'Sri Lanka', en: 'Sri Lanka', value: 'LK' },
  { it: "Stati Uniti d'America", en: 'United States', value: 'US' },
  { it: 'Sudafrica', en: 'South Africa', value: 'ZA' },
  { it: 'Sudan', en: 'Sudan', value: 'SD' },
  { it: 'Sudan del Sud', en: 'South Sudan', value: 'SS' },
  { it: 'Svezia', en: 'Sweden', value: 'SE' },
  { it: 'Svizzera', en: 'Switzerland', value: 'CH' },
  { it: 'Suriname', en: 'Suriname', value: 'SR' },
  { it: 'Swaziland', en: 'Eswatini', value: 'SZ' },
  { it: 'Tagikistan', en: 'Tajikistan', value: 'TJ' },
  { it: 'Tanzania', en: 'Tanzania', value: 'TZ' },
  { it: 'Thailandia', en: 'Thailand', value: 'TH' },
  { it: 'Timor Est', en: 'Timor-Leste', value: 'TL' },
  { it: 'Togo', en: 'Togo', value: 'TG' },
  { it: 'Tonga', en: 'Tonga', value: 'TO' },
  { it: 'Trinidad e Tobago', en: 'Trinidad and Tobago', value: 'TT' },
  { it: 'Tunisia', en: 'Tunisia', value: 'TN' },
  { it: 'Turchia', en: 'Turkey', value: 'TR' },
  { it: 'Turkmenistan', en: 'Turkmenistan', value: 'TM' },
  { it: 'Tuvalu', en: 'Tuvalu', value: 'TV' },
  { it: 'Ucraina', en: 'Ukraine', value: 'UA' },
  { it: 'Uganda', en: 'Uganda', value: 'UG' },
  { it: 'Ungheria', en: 'Hungary', value: 'HU' },
  { it: 'Uruguay', en: 'Uruguay', value: 'UY' },
  { it: 'Uzbekistan', en: 'Uzbekistan', value: 'UZ' },
  { it: 'Vanuatu', en: 'Vanuatu', value: 'VU' },
  { it: 'Vaticano', en: 'Vatican City', value: 'VA' },
  { it: 'Venezuela', en: 'Venezuela', value: 'VE' },
  { it: 'Vietnam', en: 'Vietnam', value: 'VN' },
  { it: 'Yemen', en: 'Yemen', value: 'YE' },
  { it: 'Zambia', en: 'Zambia', value: 'ZM' },
  { it: 'Zimbabwe', en: 'Zimbabwe', value: 'ZW' },
];

export const NATIONS_WITH_IMAGES = NATIONS.map(nation => ({
  ...nation,
  image: `https://flagcdn.com/w320/${nation.value.toLowerCase()}.png`,
}));
